### ISSUE TITLE
Please make config node

### ISSUE THREAD

**Issue by pastukhov** [andrei-tatar/node-red-contrib-ui#1]
It's possible to add an config node to be able configure path instead hardcoded /ui,  change header text and left menu items ?

**Comment by emiloberg** [comment]
As this is a one time setting, it should rather be in Node-RED's `settings.js` than a config node.

**Comment by emiloberg** [comment]
Spoke to soon. Saw that it was available in [config.json](https://github.com/andrei-tatar/node-red-contrib-ui/blob/master/config.json) (however, shouldn't it be in RED's settings.json?

**Comment by TotallyInformation** [comment]
The config.json file doesn't really work as it is inside the installed npm package and will therefore get replaced when updating. As Emil says, this should be in the NR settings.

**Comment by andrei-tatar** [comment]
Is this consistent with other node-red plugins? 
I know the file gets replaced on each update but is it fine to have a monolithic config file?

**Comment by emiloberg** [comment]
Yeah settings.js is how other nodes does it and it's the preferred way. See http://nodered.org/docs/configuration.html





I've been using it for a long time (e.g node-red-contrib-telldus) without any user problems. 




If the settings.js is in your Node-RED home directory it won't get overwritten when updated. 



—

**Comment by andrei-tatar** [comment]
OK, I will update the plugin to use the node settings.

**Comment by TotallyInformation** [comment]
For NR embedded use, the settings are passed to `RED.init`. This is the same as the settings.js file when used with a global install (which I don't recommend as it causes other issues including security issues). Here is an example server.js which I use to start NR on my Pi home automation system:

```
/*jshint devel: true, node: true*/

/**
  * Start an embedded Node-Red instance
  */

var http    = require('http'),
    path    = require("path"),		// Node core library. path library for cross-platform file system specs
	fs		= require("fs"),		// Node core library. Filing system library for access to files & folders on the OS
    express = require("express"),	// THE std library for serving HTTP
    RED     = require("node-red"),
	_		= require("lodash")		// lodash (improved underscore) for JS utility fns
;

// Config vars - NB: LAN details are LOCAL. If accessing from the WAN (Internet), use the WAN details instead
var mqttSrv    = '192.168.1.167',  // The LAN address for the MQTT server
    mqttWsPort = '9001',           // The LAN port for the websocket interface to the MQTT server
    nrSrv      = '192.168.1.167',  // The LAN address for this Node-Red server
    nrPort     = '1880'            // The LAN port for this systems web interface
;
var wanMqttSrv    = '192.168.1.167',  // The WAN address for the MQTT server
    wanMqttWsPort = '9001',           // The WAN port for the websocket interface to the MQTT server
    wanNrSrv      = '192.168.1.167',  // The WAN address for this Node-Red server
    wanNrPort     = '8000'            // The WAN port for this systems web interface
;

// Create an Express app
var app = express();

// Add a simple route for static content served from 'public'
app.use( "/", express.static( "public" ) );

// Add static route for bower components
app.use( '/bower_components', express.static( path.join(__dirname, '/bower_components') ) );

// Create HTTP server on port 8000 for the admin UI and any pages served by node-red
var httpServer = http.createServer( app );

// Create the settings object - see default settings.js file for other options
var nrSettings = {
    httpAdminRoot : "/red",			// Access the admin web i/f from http://<nrSrv>/red
    httpNodeRoot  : "/",			// Access other NR served pages from http://<nrSrv>/
    userDir		  : path.join(__dirname, '.nodered'),	// default: $HOME/.node-red
    nodesDir	  : path.join(__dirname, 'nodes'),		// adds extra locn, defaults are userDir/nodes & node-red/nodes
    verbose		  : true,			// For better debugging
    debugMaxLength: 2048,			// max length of debug output
	// Reorder the node pallette
    paletteCategories: [
        'subflows', 'input', 'output', 'function', 'storage', 'advanced', 'formats', 'Raspberry Pi', 'social', 'analysis'
    ],
    functionGlobalContext: {        // enables and pre-populates the context.global variable
        // os:require('os'),
        // arduino:require('duino') // directly control Arduino's over serial, https://www.npmjs.com/package/duino
        // -- Pass config variables into NR for reference -- //
        'mqttSrv'       : mqttSrv,
        'mqttWsPort'    : mqttWsPort,
        'nrSrv'         : nrSrv,
        'nrPort'        : nrPort,
        'wanMqttSrv'    : wanMqttSrv,
        'wanMqttWsPort' : wanMqttWsPort,
        'wanNrSrv'      : wanNrSrv,
        'wanNrPort'     : wanNrPort,
		// -- Pass in Libraries for convenience in function nodes -- //
        'path'          : path,		// path library for cross-platform file system specs
		'fs'			: fs,		// filing system library for access to files & folders on the OS
		'_'				: _			// lodash (improved underscore) for JS utility fns
    }
    //httpStatic: '/home/pi/node/nr/static', // only for standalone NR so not relavent here
};

// Initialise the runtime with a server and settings
RED.init( httpServer, nrSettings );

// Serve the editor UI from /red
app.use( nrSettings.httpAdminRoot, RED.httpAdmin );

// Serve the http nodes UI from /
app.use( nrSettings.httpNodeRoot, RED.httpNode );

// Make the HTTP server start listening on port 8000
httpServer.listen( nrPort );

// Start the node-red runtime
RED.start();
```

**Comment by andrei-tatar** [comment]
config.json was removed

you can add to node-red settings file:

```
ui: {
  path: 'ui', //the path for the UI (default 'ui')
  title: 'some title', //the title in the browser for the UI page (default 'Node-Red UI')
  defaultGroup: 'some name', //the default group name if none specified (default: 'Default')
}
```

**Comment by bbboki** [comment]
Hello Andrei,
I tried to change title in the browser using your instruction above, but w/o success, i.e. browser title is still "Node-RED UI". Here is snippet from /home/pi/.node-red/settings.js:

    //var fs = require("fs");

    ui = {
        path: 'ui',
        title: 'Nodered Playground',
        defaultGroup: 'some name'
    }
    
    module.exports = {
Console output when run node-red-pi :

    pi@raspberrypi:~ $ node-red-pi -v
    OPTIONS=
    ARGS= -v
    
    
    Welcome to Node-RED
    ===================
    
    19 Jan 22:29:39 - [info] Node-RED version: v0.12.5
    19 Jan 22:29:39 - [info] Node.js  version: v4.2.4
    19 Jan 22:29:39 - [info] Loading palette nodes
    19 Jan 22:29:49 - [info] Dashboard up and running
    19 Jan 22:29:52 - [info] UI started at /ui
    19 Jan 22:29:54 - [info] Settings file  : /home/pi/.node-red/settings.js
    19 Jan 22:29:54 - [info] User directory : /home/pi/.node-red
    19 Jan 22:29:54 - [info] Flows file : /home/pi/.node-red/flows_raspberrypi.json
    19 Jan 22:29:54 - [info] Server now running at http://127.0.0.1:1880/
    19 Jan 22:29:54 - [info] Starting flows
    19 Jan 22:29:54 - [info] Started flows
    
Thank you.

**Comment by bbboki** [comment]
UPDATE: oh, I should put your snippet into `module.exports = { ... }` of the settings file.
