### ISSUE TITLE
Password protection ?

### ISSUE THREAD

**Issue by natcl** [andrei-tatar/node-red-contrib-ui#10]
Is there a way to password protect the /ui endpoint ?
I've been using node-red-contrib-httpauth to password protect normal http in calls but an option to protect /ui would be great !

**Comment by andrei-tatar** [comment]
Not yet but it will be... Can't give you an estimate.

**Comment by andrei-tatar** [comment]
I checked out node-red default settings and enabling httpAuth will secure any path served by node-red. Have you tried using it?

**Comment by natcl** [comment]
Indeed.  Recently i've been using node-red-contrib-httpauth which allows to secure individual paths instead of securing all which can't be practical.  In the case of the ui I guess the default behaviour of node-red securing all is good enough.

**Comment by andrei-tatar** [comment]
OK. I'll close this issue for now.
