### ISSUE TITLE
Paragraph support for mustache ?

### ISSUE THREAD

**Issue by natcl** [andrei-tatar/node-red-contrib-ui#11]
Does the paragraph ui object supports rendering mustache templates like Node-RED's built-in template node ?
That would be a great addition to render dynamic content !

**Comment by andrei-tatar** [comment]
Not mustache, but angular templates and expressions.
You can write a template like:
```The payload is <b>{{msg.payload}}</b>```
or expressions:
```1+2={{1+2}}```

**Comment by natcl** [comment]
Thanks I'll have a look at the docs !
