### ISSUE TITLE
Add the ability to disable a widget

### ISSUE THREAD

**Issue by natcl** [andrei-tatar/node-red-contrib-ui#13]
It would be nice to have the ability to dynamically disable a widget (grey it out) via it's input.

**Comment by pastukhov** [comment]
+1

**Comment by andrei-tatar** [comment]
What would the input be?

**Comment by natcl** [comment]
Perhaps the node could receive "msg.enabled = true/false" to set this ?

**Comment by andrei-tatar** [comment]
ok, I'll consider this.

**Comment by andrei-tatar** [comment]
The latest version contains this enhancement. It works for slider/numeric/switch. I didn't want to add an input to button and button row only for this.

**Comment by natcl** [comment]
Nice thanks a lot ! Testing this right now !

**Comment by natcl** [comment]
Works great, thanks a lot for that !

**Comment by andrei-tatar** [comment]
Great! You're welcome!
