### ISSUE TITLE
Gauges

### ISSUE THREAD

**Issue by scargill** [andrei-tatar/node-red-contrib-ui#17]
Hi
I've just discovered this - and of course noted the lack of gauges etc.. but it seemed that the PARAGRAPH node would solve everything.  I tried this..

http://www.amcharts.com/demos/angular-gauge/#

Taking all that code and putting into a single html file produces a great gauge. But inserting it into the paragraph node produces nothing - absolutely nothing.  There HAS to be a way to do this... any suggestions or did I miss something?

**Comment by andrei-tatar** [comment]
Maybe the resources... Let me have a try.
Anyways, there will be a gauge component.

**Comment by andrei-tatar** [comment]
Ok, the problem is that angular doesn't support javascript injection via that method. I'll try to find some other way of executing the scripts inside the template.

**Comment by natcl** [comment]
Nice ! Thanks ! That would also allow an output to the object to send some data back to node-red ?

**Comment by andrei-tatar** [comment]
That would be possible right now with a small code change.
For example ```<button ng-click="send({payload: 'message to node-red'})"></button>``` would work (send a message to node-red on click) but I just need to add the send function on the scope of the paragraph.

**Comment by natcl** [comment]
That would be great !!

**Comment by scargill** [comment]
If you can find a way to let us run the scripts/includes etc then this opens up to being able to use any of the many html5 gadgets out there. a REALLY horrible way I'm trying now while you think about that :-) is to use an iframe - but I'm even having issues passing parameters to that.. GOT to be a way...

**Comment by scargill** [comment]
Well I ALMOST had the iframe idea working but clearly I don’t understand this handlebar stuff

 

This works – to a page that returns a gauge.

<iframe frameborder=0 scrolling="no" height="400px" src="test.html?val=45></iframe>

 

This – however just passes “{{msg.payload}}” instead of the payload ? 

<iframe frameborder=0 scrolling="no" height="400px" src="test.html?val={{msg.payload}}"></iframe>

 

Any idea where I went wrong?

**Comment by andrei-tatar** [comment]
This should work:

```<iframe frameborder=0 scrolling="no" height="400px" ng-src="{{'test.html?val=' + msg.payload}}"></iframe>```

**Comment by scargill** [comment]
You are an officer and a gentleman. Well we’re in your hands – that now works as a crude temporary measure.

 

If you are able to get scripts etc to run in there, that would be better.  Add to that some decent dials,  an RGB controller and some styling and I think you are well on the way to blowing the alternatives away!


If you need anything testing – pete at Scargill dot org

Pete.

**Comment by natcl** [comment]
scargill: you can already change the style by including some css in the paragraph node !

**Comment by scargill** [comment]
Ok will look at that, Natcl - that's at the end of my wish list...thanks. Andrei the handlebars work as you describe so now I have a working gauge - but the one I chose does not resize well, I'll find another and blog it at http://tech.scargill.net - it will do as a temporary measure. I can also add some coloured LEDs that way too.

**Comment by scargill** [comment]
Andrei can I push you just one step further.... I'm obviously not grasping the handlebars!

       <img src={{(msg.payload||1)==1 ? '"icons/light1.png"' : '"icons/light0.png"'}}>


So I made a folder with some images in it - and a straightforward IMG SRC works a treat.
        <img src="icons/light1.png">

However checking for 1 or 0 and selecting an image - produces a missing image - I've tried various combinations of quotes - could you please tell me where I've gone wrong (then I will leave you alone, honestly).

       <img src={{(msg.payload||1)==1 ? '"icons/light1.png"' : '"icons/light0.png"'}}>

**Comment by andrei-tatar** [comment]
You should again use ```ng-src```. 

Like this:
```<img ng-src="{{(msg.payload||1)==1 ? 'icons/light1.png' : 'icons/light0.png'}}">```

**Comment by scargill** [comment]
You are a hero.. but could you explain WHY so I understand… the relevance of ng-  ??

**Comment by scargill** [comment]
That works a treat. I tried to take this a stage further and let my incoming topic be the message to the LEFT of the LED - but no..

<div layout="row" layout-align="space-between">
    <p>{{msg.topic}}</p>
    <p >
       <img height="32px" ng-src="{{(msg.payload||1)==1 ? 'icons/light1.png' : 'icons/light0.png'}}">

    </p>
</div>

Do I take it you can only use one set of {{}} at a time?

**Comment by andrei-tatar** [comment]
When the browser sees the src attribute value it immediately loads a resource at that url and displays it as an image (in this case). So you can't have an expression in there. Angular has another attribute (ng-src - it's actually called a directive in the angular world) that evaluates the expression and after that it sets the actual src attribute with the result of the evaluation.

For the topic issue please post your entire template.

**Comment by scargill** [comment]
Sorry I can't seem to paste the para in - hence part of it went missing - here is an image of the whole thing the image works now but the topic does not .. I was hoping to use the topic as the left description

![green](https://cloud.githubusercontent.com/assets/1889411/11695386/bed84ede-9ea6-11e5-93e8-ac5aed6ba41b.png)

**Comment by scargill** [comment]
Incidentally I realise you are doing this for free - like my blog :-) I really appreciate your time - this opens up lots of doors.

**Comment by andrei-tatar** [comment]
The template looks fine. It should work. Are you sure you have a topic set on the incoming messages?

**Comment by scargill** [comment]
Ok, see blog – updated – off to the pub – with the knowledge needed to develop this much, much further. Thanks a lot!

 

Pete.

**Comment by andrei-tatar** [comment]
Sure, no problem. Glad it works! :+1:

**Comment by andrei-tatar** [comment]
Checkout the new Gauge node. 
It doesn't yet support customizing the colors.

**Comment by scargill** [comment]
I humbly admit defeat Andrei - your gauges may look the same as mine but yours is the superior version - marvelous - in use now.

HOWEVER. Can I ask what you did in the process to the paragraph function. My now defunct gauges no longer work...

Cannot GET /ui/gauge.html?min=0&max=40&title=Inside%20Temperature

and my not-so defunct beautiful LEDS no longer work (they show a missing image icon - code below which was working until I updated node-red-contrib-ui)..

<div layout="row" layout-align="space-between">
    <p >{{msg.topic}}</p>
    <p >
       <img height="24px" ng-src="{{msg.payload==1 ? 'icons/light1.png' : 'icons/light0.png'}}">
    </p>
</div>

**Comment by scargill** [comment]
Ok so the code isn't below - GITHUB has wiped some of it... heres a picture 

![led](https://cloud.githubusercontent.com/assets/1889411/11711707/4b867ba2-9f20-11e5-96ff-6e91d858d5c0.png)

**Comment by scargill** [comment]
Hi there - ok first issue (there's always one) apart from the above - the gauges look great on the PC but on mobile the background is not stretching for them - see image... see how the white background ends long before the 2 gauges are done.

![screenshot_2015-12-10-09-43-21](https://cloud.githubusercontent.com/assets/1889411/11712080/af1aff2e-9f22-11e5-94fd-ee87d48d2838.png)

**Comment by andrei-tatar** [comment]
I haven't changed anything to the paragraph node. Are your files in the same place (the icon images , etc.)?

I'll fix the background issue soon.

**Comment by scargill** [comment]
I didn’t move anything – just installed node-red-contrib-ui again – and… rebooted node-red…  arghhhh…

**Comment by andrei-tatar** [comment]
I fixed the page background issue. Also added masonry to layout the cards. It should look better.

**Comment by scargill** [comment]
Right it is fixed and I now know why my LEDs are not working – for reasons beyond me – the install has WIPED the previous content – so my LEDS and gauge page are no longer there!

 

I an replace them and no longer need the gauges – I am SO glad I put it all in the blog!!!

 

Right – sorted.. off to play with your gauges.

**Comment by marksev1** [comment]
Andrei-tartar, how would I change the color of the text under the gauge? Needed for a dark theme, which I did with the template node.
