### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by scargill** [andrei-tatar/node-red-contrib-ui#19]
I've been playing as you know with gauges and more... and though all of this was displaying fine on my PC - (I noticed the mobile phone was quite unresponsive... sliders taking their time and the button having to be pressed for a little time..

I figured it must be me messing with iframes and gauges.. but no. The single most effective speedup was to get rid of CHART NODE that I was updating every 2 seconds along with everything else.

Am I alone is is this known to slow things down? And how long does it keep data for?

**Comment by andrei-tatar** [comment]
The chart keeps all the data right now. 2 seconds seems too often. 
I will update it to dismiss old data based on a configuration field.

Yes, a lot of points on the chart will need a bit of processing power to be drawn on the mobile phone. And keep in mind it needs to be redrawn every 2 seconds (in your case).

For now, the chart node is more in a beta state. I would advise using it only after adding the "dismiss old data" functionality.

**Comment by scargill** [comment]
That answers that and thank you for the clarification. I’ll look forward to the changes.. Excellent.. glad it’s not me!
