### ISSUE TITLE
Not compatible with httpAdminRoot setting

### ISSUE THREAD

**Issue by mikeS7** [andrei-tatar/node-red-contrib-ui#2]
if I set httpAdminRoot in settings.js I've got "Cannot GET /admin/ui/socket.io/socket.io.js" error.

**Comment by TotallyInformation** [comment]
I've hacked a workaround by hard coding the path being passed to socket.io on line 74 of ui.js as "/red/ui/socket.io" (my admin root is /red). I added this to the Google groups thread too.

**Comment by andrei-tatar** [comment]
Will fix this.

**Comment by andrei-tatar** [comment]
Fixed by 3adf31a962ce3ad89180858c0f5de246dbcdc766
Will be available in the next release.

**Comment by mikeS7** [comment]
Broken again with 1.1.22 commit

**Comment by andrei-tatar** [comment]
Fixed by 7a91486009250b3de10afd55fbcf83313fd66c3e
