### ISSUE TITLE
Button should output msg.payload instead of msg.topic ?

### ISSUE THREAD

**Issue by natcl** [andrei-tatar/node-red-contrib-ui#20]
I find it a bit strange that the button object outputs a uuid as the payload.  Wouldn't it be more logical if the user could set the payload string in the button box and the uuid would be the msg.topic ?

**Comment by natcl** [comment]
Or perhaps it should be like you suggested for the radio button and both topic and payload should be settable in the node config ?

**Comment by andrei-tatar** [comment]
I will add a payload field in the button config.
