### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by scargill** [andrei-tatar/node-red-contrib-ui#21]
Hi Andrei

I wonder if I can get your interest up in the subject of security.  I'm using your UI - but the only problem I have that currently seems insurmountable - is security - it really needs a password for external access. I tried the various means available in Node-Red's settings file - to no avail (as of today they've updated that file to get rid of out of date instructions).

Here's a response from Nick at IBM

From: node-red@googlegroups.com [mailto:node-red@googlegroups.com] On Behalf Of Nicholas O'Leary
Sent: 10 December 2015 21:31
To: Node-RED Mailing LIst <node-red@googlegroups.com>
Subject: Re: [node-red] Re: Security

The right answer is for them to mount their ui on httpNode not httpAdmin - that way it can be secured separately to the editor. Without that fix from them there won't be much you can do without considerable work going down the 'embedding node-red' route where you can setup up security in your own app that then exposes node-red. 

Nick

**Comment by andrei-tatar** [comment]
I can mount the http-related stuff on the httpNode but keep in mind the socket.io endpoint will not be secured (you can check this by accessing the path /ui/socket.io/socket.io.js). This means that an attacker can still get full access to your node-red ui.

Also, not using HTTPS means that every time you authenticate to your node-red app over the internet, the user and the password are sent in plain text.

I strongly recommend securing the app in other ways (nginx, Apache).

**Comment by andrei-tatar** [comment]
Using httpNode in 1.1.22

**Comment by scargill** [comment]
Andrei – any chance of some control over vertical spacing – still way too much whitespace. I looked at CSS – minified – could not make head nor tail of it :)

 

Also my LED experiment – padding all wrong… and lose icons directory when you update – any chance you could add a LED option – so descrition on the left, nice LED circle on the right – could have colour depending on value with black as 0 ??

 

Pete.

**Comment by andrei-tatar** [comment]
For discussions, please use the google group (https://groups.google.com/forum/#!forum/node-red-contrib-ui). The github issues should be very specific not general chatting and this one started about security.

For the LED, you can use the paragraph node with an icon and change it's color:
```
<div layout="row" layout-align="space-between center">
    <p flex>Led</p>
    <ng-md-icon icon="wb_incandescent" ng-style="{fill:msg.payload?'red':'black'}" size="32"></ng-md-icon>
</div>
```

Thanks

**Comment by scargill** [comment]
Thanks that works – and will do…. Forum.
