### ISSUE TITLE
developer mode

### ISSUE THREAD

**Issue by KanyonKris** [andrei-tatar/node-red-contrib-ui#22]
In the Developer section of the readme you say to delete the dist folder so the minified version is not loaded. But when I do this the webpage that loads is blank and the source has paths that don't look right. I'd like to have it setup so I can edit files and test the changes with minimal steps.

**Comment by andrei-tatar** [comment]
It should work fine. After deleting the dist folder (or the index.html file inside it), you need to restart node-red.
Did you install the plugin with ```npm install node-red-contrib-ui``` or did you clone the repo?

**Comment by KanyonKris** [comment]
I cloned the repo. I will try again tonight.

**Comment by KanyonKris** [comment]
Not sure what changed or what I did different but this time it worked. Thanks for the help. I'm only so-so at programming but I'm going to try to figure out how this works. If I really get going I'll try to add a new node-red widget for another of the Angular Material widgets.
