### ISSUE TITLE
gauge decimals

### ISSUE THREAD

**Issue by KanyonKris** [andrei-tatar/node-red-contrib-ui#23]
It would be nice if I could display decimal numbers with the gauge control (i.e. 25.6 Celsius). The gauge widget has a "decimals:" property.

BTW, this is a fantastic project, good work!

**Comment by andrei-tatar** [comment]
Thanks for the nice words.
Added template field to Gauge. 
You can now write a template like:
```{{'%.1f'|sprintf:value}}°C```

To obtain
![image](https://cloud.githubusercontent.com/assets/6473183/11740979/c66f0a44-9ffe-11e5-8d44-c3418989c0a7.png)

**Comment by KanyonKris** [comment]
Very nice, thank you.

**Comment by KanyonKris** [comment]
The template above worked. I had to convert the string from MQTT to a float in node-red using a function:
> msg.payload = parseFloat(msg.payload);
> return msg;

**Comment by andrei-tatar** [comment]
The gauge actually tries to convert the number to an int. I will update it to convert the number to a float.

**Comment by tomwimmenhove** [comment]
{{'%.1f'|sprintf:value}} Leaves me with the following error:
"Error: Invalid property expression: unexpected | expression at position 6"

Did something change in recent versions? Is there a work-around?
