### ISSUE TITLE
Version 1.1.22 issue " Not compatible with httpAdminRoot setting #2" reintroduced

### ISSUE THREAD

**Issue by mikeS7** [andrei-tatar/node-red-contrib-ui#25]
Issue #2  reintroduced on version 1.1.22
I've got "Cannot GET /admin/ui/"

**Comment by dceejay** [comment]
The ui has been moved to hang off httpRoot - Only the Node-RED flow editor should hang off admin. (or other admin things... ) 
ongoing debate over in the mailing list - https://groups.google.com/forum/m/#!topic/node-red/o-tY5Dz8dK8

**Comment by mikeS7** [comment]
Thanks Dave, I've got error "404 Not Found" about "http://xxx.xxx.xxx.xxx.xxx:1880/ui/socket.io/socket.io.js" when trying to open /ui

**Comment by andrei-tatar** [comment]
The UI path is displayed when starting node-red, in the console log:
`14 Dec 09:15:14 - [info] UI started at /red/ui`

I fixed this issue, it will be in the next release.
