### ISSUE TITLE
Link to "Edit Flows" in menu is wrong

### ISSUE THREAD

**Issue by TotallyInformation** [andrei-tatar/node-red-contrib-ui#3]
Hi, like the path for socket.io, it doesn't take into account having a different location for the admin UI.

**Comment by andrei-tatar** [comment]
Will look over this. Haven't even tried node-red embedded in an app.

**Comment by TotallyInformation** [comment]
Let me know if you want my example server.js that kicks it all off.

I much prefer that method - the recommendation that Nick/Dave give to install Node-Red with -g is really an anti-pattern for node.js and I think overly complicates things, -g is really only for globally accessible utilities that might need multiple instances, something that is relatively rare with NR. The embedded way gives you much better control and puts everything in one place. It also allows you to have different versions of NR running for different instances. Great for testing new versions.

**Comment by andrei-tatar** [comment]
Fixed by 9e8b5ac7494c9248e41e3fbf8e1a20acb3f28e5d
Will be available in the next release.
