### ISSUE TITLE
Edit flow points to wrong path when httpAdminRoot in use

### ISSUE THREAD

**Issue by mikeS7** [andrei-tatar/node-red-contrib-ui#30]
Solving issue #25 broke "Edit flow" link.
Looks like commit https://github.com/andrei-tatar/node-red-contrib-ui/commit/9e8b5ac7494c9248e41e3fbf8e1a20acb3f28e5d should be changed a bit

**Comment by andrei-tatar** [comment]
Edit flow will actually be removed.
But there will be a way of adding custom button links on that same spot.
I, for example, expose only the node-red ui on the internet and not the node-red editor so there's no point in having the "Edit flow" button.
