### ISSUE TITLE
Sub flow usage duplicates Tabs

### ISSUE THREAD

**Issue by emms007** [andrei-tatar/node-red-contrib-ui#32]
Hello,

I am using node-red-contrib-ui as a subflow and it seems to be issue managing its tabs.

[Context]
Node-red overall configuration logic is as follow:
1. [one main flow to process events generated from multiple source systems]=> contains a call to contrib-ui subflow, as an output, to update some UI text with latest status
2. [one main flow to process user events]=> calls contrib-ui subflow as an input, which is expected to push contrib-ui events (buttons)

Contrib-ui subflow is configured to output all its content to TAB1. 

[Issue]
The /ui interface show twice the TAB1 in tab selection list, as if one was created each time the subflow is being called.
The two tabs displays the same information, but in one of them buttons are not working, while in the other one, the text output is not getting updated (again, this split is following each of the subflow call expected action).

Please let me know if providing screenshots would help out.
- Emms007

**Comment by andrei-tatar** [comment]
I'm guessing you have multiple ui_tab configuration nodes created for each sub-flow.
Could you please post a simplified flow that reproduces your issue?

**Comment by emms007** [comment]
Yes they seems to have multiple ui_tab configured, however I have only one.

Below is a simplified flow:

Issue32_Parent1 [will keep showing latest timestamp]:
`[{"id":"87687c60.78978","type":"ui_tab","z":"c2cf6e14.3d309","name":"Issue32_TAB","icon":"dashboard","order":"1"},{"id":"c2cf6e14.3d309","type":"subflow","name":"Issue32_Subflow","info":"","in":[{"x":293,"y":241,"wires":[{"id":"8ca2da8f.735d28"}]}],"out":[{"x":534,"y":172,"wires":[{"id":"21729e88.de8d62","port":0}]}]},{"id":"21729e88.de8d62","type":"ui_button","z":"c2cf6e14.3d309","tab":"87687c60.78978","name":"Button","payload":"ButtonPushed!","topic":"","group":"","order":1,"x":418,"y":164,"wires":[[]]},{"id":"8ca2da8f.735d28","type":"ui_text","z":"c2cf6e14.3d309","tab":"87687c60.78978","name":"DisplayTimeStamp","group":"","order":1,"format":"{{msg.payload}}","x":430,"y":248,"wires":[]},{"id":"75a2e17e.8a5d2","type":"subflow:c2cf6e14.3d309","z":"5fe964a.fa0169c","name":"","x":404.5,"y":205.5,"wires":[[]]},{"id":"9ffb3660.6004c8","type":"inject","z":"5fe964a.fa0169c","name":"PushTimestampEvery2Sec","topic":"","payload":"","payloadType":"date","repeat":"2","crontab":"","once":false,"x":172,"y":223,"wires":[["75a2e17e.8a5d2"]]}]`

Issue32_Parent2 [will debug out a button has been pushed]:
`[{"id":"87687c60.78978","type":"ui_tab","z":"c2cf6e14.3d309","name":"Issue32_TAB","icon":"dashboard","order":"1"},{"id":"c2cf6e14.3d309","type":"subflow","name":"Issue32_Subflow","info":"","in":[{"x":293,"y":241,"wires":[{"id":"8ca2da8f.735d28"}]}],"out":[{"x":534,"y":172,"wires":[{"id":"21729e88.de8d62","port":0}]}]},{"id":"21729e88.de8d62","type":"ui_button","z":"c2cf6e14.3d309","tab":"87687c60.78978","name":"Button","payload":"ButtonPushed!","topic":"","group":"","order":1,"x":418,"y":164,"wires":[[]]},{"id":"8ca2da8f.735d28","type":"ui_text","z":"c2cf6e14.3d309","tab":"87687c60.78978","name":"DisplayTimeStamp","group":"","order":1,"format":"{{msg.payload}}","x":430,"y":248,"wires":[]},{"id":"792fb1dd.86d05","type":"subflow:c2cf6e14.3d309","z":"851a9389.7ae57","x":292,"y":201,"wires":[["10d096de.ef2f69"]]},{"id":"10d096de.ef2f69","type":"debug","z":"851a9389.7ae57","name":"ShowPushedButtonValue","active":true,"console":"false","complete":"payload","x":512,"y":188,"wires":[]}]`

Issue32_Subflow [contains text holder for timestamp, and button]
`should be included in above exports`

Screenshot Demo:
![Demo](http://ibin.co/2Q9GGskC5v3X)

-Emms007

**Comment by andrei-tatar** [comment]
As I suspected, you have a duplicate ui_tab config node for each subflow.
Open one of the subflows, edit the ui_tab config node (edit a node, and edit the tab).
![image](https://cloud.githubusercontent.com/assets/6473183/11841879/bf29f006-a408-11e5-86ac-abeb34dcbc32.png)
I top-right drop-down make sure to select "on all flows"
Now go to the other sub-flow and change it to use that tab that is on all the flows.

**Comment by emms007** [comment]
Thanks this definitely helped, not it show only one tab, but with duplicated content (half operative as before):

![image](https://cloud.githubusercontent.com/assets/171033/11843192/7862ae38-a408-11e5-87be-8a76524e4a1a.png)

Did you get it OK on your side? 
-Emms007

**Comment by andrei-tatar** [comment]
That is supposed to happen. This is because each sub-flow creates new instances of nodes within them. So adding the same sub-flow twice will result in 2 different buttons!
