### ISSUE TITLE
Feature request: Switch externally defined value

### ISSUE THREAD

**Issue by emms007** [andrei-tatar/node-red-contrib-ui#33]
Hello,

I can see that the Switch UI element has an input. I tried to push the On/Off value it expects there, but it is not doing much. 
==> Is there a way that pushing the related On/Off value to the switch would update its status?

[Contextual usage case]
- Contrib-UI is being used as another central system management GUI
- Contrib-UI contains a On/Off switch to trigger lamps
- Those lamps may be updated through other MQTT inputs (domoticz, json calls etc)
- Updating the On/Off status of the switch in Contrib-UI would ensure that it is showing the latest known state across the sytems

Kudos & thanks !
- Emms007

**Comment by andrei-tatar** [comment]
That should already be working.
You can try this flow:
```json
[{"id":"53020cc1.acfdf4","type":"ui_tab","z":"4880859c.b77f7c","name":"Home","icon":"dashboard","order":"1"},{"id":"fdd6325e.0229d","type":"ui_button","z":"4880859c.b77f7c","tab":"53020cc1.acfdf4","name":"On","payload":"on","topic":"","group":"","order":1,"x":276,"y":111,"wires":[["bea9f5f3.415608"]]},{"id":"afe6dbfa.501928","type":"ui_button","z":"4880859c.b77f7c","tab":"53020cc1.acfdf4","name":"Off","payload":"off","topic":"","group":"","order":"2","x":274,"y":167,"wires":[["bea9f5f3.415608"]]},{"id":"bea9f5f3.415608","type":"ui_switch","z":"4880859c.b77f7c","tab":"53020cc1.acfdf4","name":"Switch","topic":"","group":"","order":"3","onvalue":"on","offvalue":"off","x":457,"y":130,"wires":[[]]}]
```

**Comment by emms007** [comment]
Hello,
Indeed it works, I got confuse looking at an inoperative switch from issue #32 
Emms007
