### ISSUE TITLE
node-red-contrib-ui: ui_paragraph remnant

### ISSUE THREAD

**Issue by Toshibass** [andrei-tatar/node-red-contrib-ui#35]
I was just going through the node-red log for other reasons but spotted this :

19 Dec 20:35:09 - [info] Loading palette nodes
19 Dec 20:35:15 - [info] UI started at /ui
19 Dec 20:35:20 - [warn] Missing node modules:
19 Dec 20:35:20 - [warn]  - node-red-contrib-ui: ui_paragraph
19 Dec 20:35:20 - [info] Removing modules from config

Looking back its been doing this since 15 Dec when the updated template node was introduced.
My current ui version is  1.2.5

Is this a remnant in the ui code that needs to be addressed ?

**Comment by andrei-tatar** [comment]
No. Node-red keeps a ```~/.node-red/.config.json``` file that you need to delete in order for the warning to go away (it's recreated next time you start node-red).
