### ISSUE TITLE
Gauge does not allow html encoded values

### ISSUE THREAD

**Issue by TotallyInformation** [andrei-tatar/node-red-contrib-ui#37]
Hi, UI is coming along really nicely! Getting to be very useful.

One small issue, the gauge node has no way of showing a unit such as "&deg;C" even though it happily accepts and correctly displays trailing text. Numeric and text nodes allow this.

Would it be possible to get a fix?

**Comment by andrei-tatar** [comment]
The problem is not really with node-red-contrib-ui, but with "justgage". I'll try and see if I can make a "hackish" fix from this side.
You cand display those symbols if you paste the text directly in the template.
So instead of "{{value}} &deg;C" you can use "{{value}} °C".

**Comment by TotallyInformation** [comment]
Ah, good call Andrei, thanks.
