### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by TotallyInformation** [andrei-tatar/node-red-contrib-ui#4]
I've put these into the [Google group](https://groups.google.com/forum/#!topic/node-red/dcljG1d3VQQ) as well. I've not included the issues here, I've raised those in separate posts.

- Allow ordering of both entries in a group and the groups themselves.

   It is really important to give some simple measure of control so that data can be shown in a logical fashion otherwise the UI will be extremely limited.

- Allow more features in the template fields

   - fprint style formatting would be very useful so that things line up such as numbers with decimal places. 

   - Allow html encoded entities such as &deg; or &#x2122; The former is especially useful for home automation and other IoT projects (note that GitHub markdown has interpreted those entities correctly)

   - See also the comments about making more variables (e.g. msg.xxxx) available

- I know that Material Design is meant to be flat but I think the button is just TOO flat, it isn't at all clear that there is a button present - poor UI design. No point in having a button unless users understand it *is* a button.

- Switch buttons - It would be great if there were some additional configuration options
   - Such as being able to define the return values for the switch so that the output could be fed directly into a controller (e.g. "On"/"Off" or "on"/"off", etc.)

- Have an input field for msg.topic on all nodes with output. By default pass-through nodes should pass the topic through but it is really helpful to be able to put your own topic in. Again, because this is widely used by things such as MQTT, it would enable the output to be sent directly to an MQTT node.

   Because there is no msg.topic, debugging may also be hard, especially when chaining things together since any debug output can't identify the source (it would mean having to put a single debug node for every output).

- For nodes that take an input msg:

   - Allow overrides on the label and group fields from the input msg.

     That way for example, you could connect a range of input MQTT messages (each has a topic) to a range of output messages without having to set up each separately. This should be possible since groups and elements appear dynamically. They would disappear of course on a page reload but that's OK.

   - Allow more variables in the template. Perhaps just exposing the msg variable so that we could do something like, on a text output node for example:

        ```Temperature: {{msg.payload.temperature}}, From: {{msg.topic}}``` 

   - Being able to set the "value" element from a specific msg variable would save some additional processing nodes. Let's say that the temperature was on the msg.payload as in the example above. In this case, the "value" input field in the node would be set to "msg.payload.temperature"

- The nodes that take input and produce output (number, slider, switch) 

   - don't trigger output when a new input is provided, only when the user changes something. That seems inconsistent to me and personally I would much prefer to get output on any change so that automated and manual inputs produce the same output.

Hope at least some of these will be possible - I'll add any others as I think of them.

**Comment by andrei-tatar** [comment]
> Allow ordering of both entries in a group and the groups themselves.

I agree. This will be added.

> Allow more features in the template fields
>   - fprint style formatting would be very useful so that things line up such as numbers with decimal places. 

I'll consider this but this is not a high priority.

> Allow html encoded entities such as &deg; or &#x2122; The former is especially useful for home automation and other IoT projects (note that GitHub markdown has interpreted those entities correctly)

I added this. It now supports any valid HTML.

> See also the comments about making more variables (e.g. msg.xxxx) available

This is already supported.

> I know that Material Design is meant to be flat but I think the button is just TOO flat, it isn't at all clear that there is a button present - poor UI design. No point in having a button unless users understand it *is* a button.

I will look over making the button more visible.

> Switch buttons - It would be great if there were some additional configuration options
> Such as being able to define the return values for the switch so that the output could be fed directly into a controller (e.g. "On"/"Off" or "on"/"off", etc.)

OK.

> Have an input field for msg.topic on all nodes with output. By default pass-through nodes should pass the topic through but it is really helpful to be able to put your own topic in. Again, because this is widely used by things such as MQTT, it would enable the output to be sent directly to an MQTT node.

I don't like adding fields that have no relevance to a specific node. Topic means nothing for the UI.

> Because there is no msg.topic, debugging may also be hard, especially when chaining things together since any debug output can't identify the source (it would mean having to put a single debug node for every output).

I believe there is a node that sets a property on a message (or use a function node).

> For nodes that take an input msg:
>   - Allow overrides on the label and group fields from the input msg.
>     That way for example, you could connect a range of input MQTT messages (each has a topic) to a range of output messages without having to set up each separately. This should be possible since groups and elements appear dynamically. They would disappear of course on a page reload but that's OK.

There will be a paragraph control that could be used for this, show only text.

>   - Allow more variables in the template. Perhaps just exposing the msg variable so that we could do something like, on a text output node for example:
>        ```Temperature: {{msg.payload.temperature}}, From: {{msg.topic}}``` 
>   - Being able to set the "value" element from a specific msg variable would save some additional processing nodes. Let's say that the temperature was on the msg.payload as in the example above. In this case, the "value" input field in the node would be set to "msg.payload.temperature"

This is already done but not this way. ```msg.payload``` becomes ```value```. I don't want to send the entire ```msg``` because it can also contain things like socket ids and a lot of other irelevant stuff. The payload is all that should matter. If you want to send the topic, add it to the payload.
If you have ```msg.payload.temperature``` you can simply change the template to ```{{value.temperature}}```. You can also use expressions. 

>- The nodes that take input and produce output (number, slider, switch) 
>   - don't trigger output when a new input is provided, only when the user changes something. That seems inconsistent to me and personally I would much prefer to get output on any change so that automated and manual inputs produce the same output.

This needs to be fixed.

>Hope at least some of these will be possible - I'll add any others as I think of them.
Thanks for the feedback!

**Comment by TotallyInformation** [comment]
> See also the comments about making more variables (e.g. msg.xxxx) available
   >> This is already supported.

Ah! I can see from later on that `value` can be an object. Hadn't thought of that. Hopefully that will be made clear in the documentation.

> Have an input field for msg.topic on all nodes with output. By default pass-through nodes should pass the topic through but it is really helpful to be able to put your own topic in. Again, because this is widely used by things such as MQTT, it would enable the output to be sent directly to an MQTT node.
>> I don't like adding fields that have no relevance to a specific node. Topic means nothing for the UI.

But for any field with OUTPUT, it IS relevant! Since you may be passing information along to other nodes that DO use the topic. Topic is a key concept for Node-Red and is widely used. Without this, you have to mess around with other nodes - quite possibly a function node with coding - just to get something simple to work. That negates using UI in the first place.

> Allow more variables in the template. Perhaps just exposing the msg variable so that we could do something like, on a text output node for example: Temperature: {{msg.payload.temperature}}, From: {{msg.topic}}
Being able to set the "value" element from a specific msg variable would save some additional processing nodes. Let's say that the temperature was on the msg.payload as in the example above. In this case, the "value" input field in the node would be set to "msg.payload.temperature"

>> This is already done but not this way. msg.payload becomes value. I don't want to send the entire msg because it can also contain things like socket ids and a lot of other irrelevant stuff. The payload is all that should matter. If you want to send the topic, add it to the payload.
>> If you have msg.payload.temperature you can simply change the template to {{value.temperature}}. You can also use expressions.

OK, that wasn't clear.

Sending the topic through that way is not the way that people expect Node-Red to work. msg.topic is on a par with msg.payload and generally expected to be passed through. It is used to control output typically. It is meta-data rather than data (which **should** all be on msg.payload). Node-Red has worked this way from the outset. It's lack can greatly complicate processing.

I do sometimes copy the topic to the payload in cases where the processing node may change it and I need to keep track of the original topic. However, that is an exception not the normal rule.


Anyway, great stuff, thanks for responding.

**Comment by andrei-tatar** [comment]
I implemented almost all of the requests.

> Sending the topic through that way is not the way that people expect Node-Red to work. msg.topic is on a par with msg.payload and generally expected to be passed through. It is used to control output typically. It is meta-data rather than data (which **should** all be on msg.payload). Node-Red has worked this way from the outset. It's lack can greatly complicate processing.

> I do sometimes copy the topic to the payload in cases where the processing node may change it and I need to keep track of the original topic. However, that is an exception not the normal rule.

I can't find any standard node that has a topic field on it other than MQTT. Topic is MQTT specific.
Just to be clear, if a message is forwarded, it's not changed. So if an input message has a ```.topic``` property, the output message will also have it. If the output message is generated from scratch as a result of an UI event (button click, slider value changed, etc.) it will only contain the new value as the payload.

If you check the General guidance for creating nodes (<http://nodered.org/docs/creating-nodes/>), it states:

>Nodes should be well-defined in their purpose.
>A node that exposes every possible option of an API is potentially less useful that a group of nodes that each serve a single purpose.

Adding the topic to a message is MQTT specific and is not related in any way with the UI.

**Comment by andrei-tatar** [comment]
I just published version 1.1.0.
I'll close this issue. If there is anything else, please create separate issues.
Thanks for the great feedback!

**Comment by TotallyInformation** [comment]
Thanks. 

BTW, Topic is on the inject node and used on debug output. MQTT is the original driver for Node-Red. It was designed to showcase the possibilities of MQTT for IBM.
