### ISSUE TITLE
Cannot add html encoded characters to template

### ISSUE THREAD

**Issue by TotallyInformation** [andrei-tatar/node-red-contrib-ui#5]
You can't include an HTML encoded or unicode symbol e.g. &deg; or &#x2122; in a template.

This is particularly needed for IoT and home automation UI's as the degree symbol is very commonly needed.

**Comment by andrei-tatar** [comment]
I will add ability to define the template as HTML code.

**Comment by andrei-tatar** [comment]
Fixed in 84e57024ed12078de3b5653f890ddddcfbb45b4f
Will be available in the next release.

**Comment by TotallyInformation** [comment]
Great stuff, thanks.
