### ISSUE TITLE
Enhancement Suggestion: Switch - output name

### ISSUE THREAD

**Issue by TotallyInformation** [andrei-tatar/node-red-contrib-ui#7]
Hi again Andrei, many thanks for the updates. Everything is working fairly well and the extra configuration options are welcome.

However, leaving aside the discussion on topic. Would it at least be possible to pass the NAME of the switch through to the output. Currently this isn't happening. So the output message on triggering a switch is something like:

```
17/11/2015, 21:52:168e3dbf63.71c24
msg : Object
{ "payload": "On", "_msgid": "22872024.dd78e" }
```

Notice that there is no way of identifying the source of the message which means that to feed this into a single downstream node (maybe to store into a database or more likely to send to MQTT) requires an extra processing step FOR EACH SWITCH. 

For example, if I have a few switches:

```
[MQTT in "SWITCHES/#"] -> [Switch node] -+-> [UI Switch 1]  ->[Change: topic]-+
                                         |                                    |
                                         +-> [UI Switch 2] -->[Change: topic]-+-->[MQTT]
                                         ... etc ...          ... etc...      |
```

So if I have 10 switches, that's an extra 10 nodes (the change nodes) I have to set that, if your UI Switch node set the topic from the name, I could avoid. At worst, I would put in a single change or template node instead that altered the name to a suitable topic.

msg.topic would be the best for that but msg.name wouldn't be too bad either.

Am I making sense? Passing the name downstream as meta-data allows more intelligent flow processing for minimal code.

**Comment by andrei-tatar** [comment]
OK. I'll add a topic field to each node that has an output.

**Comment by andrei-tatar** [comment]
Resolved in latest release.
