### ISSUE TITLE
Can't see layout on Mac or Raspberry pi

### ISSUE THREAD

**Issue by natcl** [andrei-tatar/node-red-contrib-ui#8]
Tried installing but I get the following error:
```
sudo npm install -g node-red-contrib-ui
/usr/local/lib
└─┬ node-red-contrib-ui@1.1.3
  ├── UNMET PEER DEPENDENCY angular-animate@^1.3.15 || >1.4.0-beta.0
  ├── UNMET PEER DEPENDENCY angular-aria@^1.3.15 || >1.4.0-beta.0
  ├─┬ angular-material-icons@0.6.0
  │ └── angular@1.4.8
  └── angular-sanitize@1.4.8

npm WARN EPEERINVALID angular-material@0.11.4 requires a peer of angular-animate@^1.3.15 || >1.4.0-beta.0 but none was installed.
npm WARN EPEERINVALID angular-material@0.11.4 requires a peer of angular-aria@^1.3.15 || >1.4.0-beta.0 but none was installed.
```

**Comment by andrei-tatar** [comment]
I haven't tried installing on a Mac or RPi but I'm working on removing the angular* dependencies. Actually making them dev dependencies.
I'll let you know when you can try installing it again.

**Comment by andrei-tatar** [comment]
The latest release should depend on angular only if you're a developer.
Let me know if you encounter any issues.
Why do you install the package globally?

**Comment by natcl** [comment]
Thanks ! Works like a charm now.
My node-red is installed globally that's why I installed it globally too
