### ISSUE TITLE
Customize slider update rate ?

### ISSUE THREAD

**Issue by natcl** [andrei-tatar/node-red-contrib-ui#9]
Would it be possible to customize the update rate of the slider ?
The default seems to be a bit slow ?

**Comment by andrei-tatar** [comment]
By default it sends the value after it hasn't been changed for 200 ms. This is because sliding it with the mouse would send a lot of updates. What do you think a good delay would be?

**Comment by natcl** [comment]
perhaps 50ms ?

**Comment by andrei-tatar** [comment]
I just published 1.1.11 which contains the update to 50 ms.

**Comment by natcl** [comment]
We just did some more tests, we're using the sliders to control audio volumes and at 50ms it sounds a bit choppy.  
I tried at 10ms and it's much smoother.  Would you be willing to go at 10ms ?  It doesn't seem to affect performance.

**Comment by andrei-tatar** [comment]
Sure. Just send in a pull request.
